# 可以负载服务
upstream backend_servers {
    server 192.168.1.108:8101;
}

server {
    listen 80;

    server_name 192.168.1.104;  # 修改为你的实际服务器 IP 或域名【域名需要备案】

    location /sse {
        # 验证apikey参数，这个apikey也可以对接服务端接口来处理。
        if ($arg_apikey != "DElk89iu8Ehhnbu") {
            return 403; # 如果apikey不正确，返回403禁止访问
        }

        # 重写URL，去掉apikey参数
        rewrite ^(/sse/)\?apikey=.* $1 break;

        proxy_pass http://backend_servers;  # 将请求代理到上游服务器组
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        chunked_transfer_encoding off;
        proxy_buffering off;
        proxy_cache off;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /mcp/message {
        proxy_pass http://backend_servers;  # 将请求代理到上游服务器组
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

}